### PR TITLE
BAH-1712 | Add docker-compose architectural diagram

### PR DESCRIPTION
**Pull request by NoorShiuli**
Created the architectural diagram with ports and volumes using https://github.com/pmsipilot/docker-compose-viz.
Took reference from : https://dev.to/krishnakummar/creating-block-diagrams-from-docker-compose-files-7kf

cc: @manishkumar1509

### CODE REVIEW

**Comment by NoorShiuli** [comment]
Raised PR, please review. @N0-man @gsluthra @angshu @mohan-13

**Comment by gsluthra** [comment]
This is a sample screenshot of the PDF diagram. Very interesting. 
image

**Comment by gsluthra** [comment]
The hope was that we would have an automated way of generating the latest diagram, or have a script that can be run to generate the diagram easily, as the docker-compose file keeps getting modified. In this PR, i think a static diagram has been committed as a PDF. Would you instead provide a script/command that autogenerates it on demand?

**Comment by NoorShiuli** [comment]
> The hope was that we would have an automated way of generating the latest diagram, or have a script that can be run to generate the diagram easily, as the docker-compose file keeps getting modified. In this PR, i think a static diagram has been committed as a PDF. Would you instead provide a script/command that autogenerates it on demand?

Yeah sure. Then, should we add the script in the Readme file? 
Also, should we keep the static images for now as a reference?

**Comment by gsluthra** [comment]
You can add a script in readme for now. Or provide a script in a separate sub-folder that generates this. And commit the current PDF there.

**Comment by NoorShiuli** [comment]
@gsluthra While running the script we are getting the below error:
```
In Parser.php line 234:
                                                                                                                                                                          
  Reference "default   # update this value to *loki if needed to see logs in grafana dashboard." does not exist at line 15 (near "<<: *default   # update this value to   
  *loki if needed to see logs in grafana dashboard.").                              
```
There seems to be an issue with the schema validation of the yaml file. On removing ` <<: *default   ` (line n. 15), script works fine.
Can you check on this?

**Review by gsluthra — APPROVED** [review]

**Comment by gsluthra** [comment]
Thanks a lot @NoorShiuli .

@mohan-13 - I approved this. Can u also review and then merge?

**Comment by mohan-13** [comment]
> @gsluthra While running the script we are getting the below error:
> 
> ```
> In Parser.php line 234:
>                                                                                                                                                                           
>   Reference "default   # update this value to *loki if needed to see logs in grafana dashboard." does not exist at line 15 (near "<<: *default   # update this value to   
>   *loki if needed to see logs in grafana dashboard.").                              
> ```
> 
> There seems to be an issue with the schema validation of the yaml file. On removing `<<: *default ` (line no. 15 in docker-compose.yml file inside bahmni-docker folder), script works fine. Can you check on this?

Is the comment in that line causing problem ? If so,  can you try adding ## and check once? Also try to move the comment to a new line above and check if that helps ?

**Comment by mohan-13** [comment]
Also if we want the process to be automated, we could also leverage Github Actions to run on change to docker-compose file and commit the new diagram automatically from Github Actions. What do you think @gsluthra ?

**Comment by NoorShiuli** [comment]
> > @gsluthra While running the script we are getting the below error:
> > ```
> > In Parser.php line 234:
> >                                                                                                                                                                           
> >   Reference "default   # update this value to *loki if needed to see logs in grafana dashboard." does not exist at line 15 (near "<<: *default   # update this value to   
> >   *loki if needed to see logs in grafana dashboard.").                              
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > There seems to be an issue with the schema validation of the yaml file. On removing `<<: *default ` (line no. 15 in docker-compose.yml file inside bahmni-docker folder), script works fine. Can you check on this?
> 
> Is the comment in that line causing problem ? If so, can you try adding ## and check once? Also try to move the comment to a new line above and check if that helps ?

Moving the comment to a new line above has solved the problem. Thanks @mohan-13. We have pushed the changes.

**Comment by gsluthra** [comment]
Yes @mohan-13 - would be good to run the command as part of a Github Action, and auto-commit to repo, but that can be a separate PR.

**Comment by mohan-13** [comment]
Thanks a lot for the PR @NoorShiuli !

**Pull request merged**
